### ISSUE TITLE
Is there a way to create videos after syncing multiple observatory images and plotting them on a map?

### ISSUE THREAD

**Issue by ksd3** [mshumko/asilib#17]
For example, [this](https://aurora-asi-lib.readthedocs.io/en/latest/_images/map_arc.png) but everything is time synced.

**Comment by mshumko** [comment]
Hi @ksd3,

Good timing on the feature request. The [image syncing](https://github.com/mshumko/asilib/blob/b9048101104c16117b8a3ca9ad0eb660266807fc/asilib/imagers.py#L239-L311) is already implemented in a development branch, and I will keep you updated once I implement the animation code.

**Comment by mshumko** [comment]
As an update @ksd3, I have a prototype [Imagers.animate_map() and Imagers.animate_map_gen()](https://github.com/mshumko/asilib/blob/c0fc97ed57086e29b7fe2aa3c6db0f02b42abb10/asilib/imagers.py#L150-L374) written, but I am still debugging the implementation before I release a new version of the library. The mosaics don't look quite right if there are missing images or the imagers become desynchronized.

You're welcome to try it out by installing asilib from the `animate_imagers` branch.

**Comment by ksd3** [comment]
Thanks, I was waiting for this!
