### ISSUE TITLE
Relax dependency requirements?

### ISSUE THREAD

**Issue by jameswilburlewis** [mshumko/asilib#20]
I would like to show an example or two using asilib at the upcoming PyHC summer school.   All the notebooks we present should run in the shared PyHC environment we're setting up.   There is a rather narrow range of versions for the various PyHC package dependencies that will allow them to coexist in the same environment.  Looking at the asilib requirements.txt, I see that many of asilib's dependencies are pinned to exact versions, and I'm 99% sure that's going to cause a conflict if we try to install asilib in the shared environment.  Would it be possible to turn some of those "==" dependencies into lower bounds?

Great package, by the way!  Have you considered using pyspedas to do some of the data downloads, to take advantage of it's ability to cache data files and only download them if needed?

**Comment by mshumko** [comment]
Hi @jameswilburlewis,

The `requirements.txt` file specifies the dependencies for the developer environment which I purposefully pinned to exact versions, while the `pyproject.toml` specifies looser requirements for users. For your PyHC environment, may I suggest that you install asilib via `python3 -m pip install asilib`, or `python3 -m pip install .` from in the `asilib/` directory.

Please let me know if you run into any trouble installing the package, or if you'd like me to loosen any dependencies in `pyproject.toml`.

P.S. I plan to attend at least a part of the PyHC summer school, and if necessary I am happy to help out with your examples. Reproducing results from well-known papers is always a joy.

P.S.S. Thank you for the appraise! While asilib has a downloader built-in already, I have not considered using pyspedas as an alternative downloader. Is this the [function](https://github.com/spedas/pyspedas/blob/e5572b79dee4392ec733a749a8714d77b8db792c/pyspedas/utilities/download.py#L212) that handles downloading for all missions that pyspeas supports?

**Comment by jameswilburlewis** [comment]
After opening the issue, I did see the looser requirements in pyproject.toml.   I asked Shawn Polson to take a look, and he did see some conflicts (he didn't mention what they were, though...) Maybe it's better not to try fitting it into the environment at this late date...we can revisit the issue after summer school is over.    I will still generate a few movies for my presentation and mention how I did them with asilib; we just won't use that package for any of the live demos under the PyHC environment.   We're focusing on the March 24, 2023 event -- there were clear skies over Canada that morning, and some very nice imagery from several of the THEMIS ASI sites!

Yes, download.py is the main routine PySPEDAS uses for downloading data.   There's a load routine themis.ground.ask() for loading keograms;  I should probably add a few more routines for loading the  THEMIS ASI data, maybe also the REGO or T-rex datasets.   Then all you'd have to do is call the top level load routines, and pull the data arrays out of the returned tplot variables, rather than writing code do call download() then doing your own cdf processing....

I'm working on implementing field line tracing in pyspedas using the geopack package.   That might come in handy for animating conjunctions using magnetic foot points.

I'll go ahead and close this issue....I'll be sure to let you know when I've added some more ASI support to pyspedas.  Meanwhile, if you have future updates for asilib, I'd be happy to help test them!

**Comment by mshumko** [comment]
Would you mind asking Shawn to share what the conflicts are? I can experiment with relaxing the dependencies. And do you see an immediate benefit to merging asilib into PyHC before the summer school? I've been meaning to do it, and I can commit some time now to the merge.

I'll be happy to utilize your field line tracing code so please keep me updated. And we should chat later about how to download the data. To my knowledge the REGO and TREx data can only be accessed from [Calgary's site](https://data.phys.ucalgary.ca/sort_by_project/) which has a non-trivial folder structure. Specifically, one of the parent folders of the data is, for example, `kapu_themis21/`, where the "21" has to be deduced using regular expressions on the hrefs.
